#!/usr/bin/python

from subprocess import Popen, PIPE
from shlex import split
from sys import argv

needle = argv[1].upper()
files = argv[2:]

for file in files:
    text = Popen(split('/usr/bin/pdf2txt "'+file+'"'), stdout=PIPE).communicate()[0]
    if needle in text.upper():
        print file
